package centrodeportivo.gui.controladores.principal;

public enum IdPantalla {
    PANTALLAPERSOAL,
    PANTALLASOCIO,
    INICIO,
    NOVOUSUARIO,
    ADMINISTRARUSUARIOS,
    MENSAXES,
    NOVOMENSAXE,
    NOVATARIFA,
    ADMINISTRARTARIFAS,
    CUOTA,
    RESUMENREXISTROS,
    NOVOREXISTRO,
    ELIMINARREXISTRO,
    NOVAINCIDENCIA,
    ADMINISTRARINCIDENCIAS,
    ADMINISTRARCAPACIDADES
}
