package centrodeportivo.gui.controladores.principal;

public enum IdPantalla {
    PANTALLAPERSOAL,
    PANTALLASOCIO,
    INICIO,
    NOVAINSTALACION,
    ADMINISTRARINSTALACIONS,
    EDITARINSTALACION,
    ADMINISTRARTIPOSACTIVIDADES,
    INSERCIONTIPOACTIVIDADE,
    NOVOMATERIAL,
    NOVAAREA,
    NOVAAREA1

}
