package centrodeportivo.auxiliar;

/**
 * @author David Carracedo
 * @author Daniel Chenel
 */

public enum IdPantalla {
    PANTALLAPERSOAL,
    PANTALLASOCIO,
    INICIO,
    USUARIO,
    ADMINISTRARUSUARIOS,
    MENSAXES,
    NOVOMENSAXE,
    XESTIONTARIFA,
    ADMINISTRARTARIFAS,
    CUOTA,
    RESUMENREXISTROS,
    NOVOREXISTRO,
    ELIMINARREXISTRO,
    NOVAINCIDENCIA,
    ADMINISTRARINCIDENCIAS,
    ADMINISTRARCAPACIDADES,
    XESTIONINCIDENCIA
}
